apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: shipay-letsencrypt
  namespace: cert-manager
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: caio20122011@gmail.com
    privateKeySecretRef:
      name: shipay-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
