name: Build and Deploy to GCP
on:
  workflow_dispatch:


env:
  REPOSITORY_NAME: challenge-shipay-devops

jobs:
  build-and-push-gcp:
    name: Build and publish Docker image to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ env.REPOSITORY_NAME }}
        tags: |
          type=sha,enable=true,prefix=shipay-,suffix=,format=short

    - name: Build image and push Google Cloud
      uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
      with:
        registry: ${{ secrets.GCP_ARTIFACT_REGISTRY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}
        image_name: ${{ env.REPOSITORY_NAME }}
        image_tag: ${{ steps.meta.outputs.version }}
        context: ./devops/garapua/base-test-api

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push-gcp
    steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_LOCATION }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${{ env.REPOSITORY_NAME }} ${{ env.REPOSITORY_NAME }}=${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ env.REPOSITORY_NAME }}:${{ steps.meta.outputs.version }}
        kubectl rollout status deployment/${{ env.REPOSITORY_NAME }}
