name: Horusec SAST

on:
  workflow_dispatch:

jobs:
  horusec-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Horusec
        run: |
          curl -sSfL https://github.com/ZupIT/horusec/releases/latest/download/horusec_linux_amd64 -o horusec
          chmod +x horusec
          sudo mv horusec /usr/local/bin/horusec

      - name: Rodar Horusec SAST
        run: |
          horusec start -p ./ --config-file-path="./horusec-config.json" --log-level=info --information-severity=true
