name: Bandit SAST

on:
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Altere para a versão desejada do Python

      # Passo 3: Instalar dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Se você tiver um arquivo de dependências

      # Passo 4: Instalar o Bandit
      - name: Install Bandit
        run: |
          pip install bandit

      # Passo 5: Rodar a análise Bandit
      - name: Run Bandit SAST
        run: |
          bandit -r . -o devops/garapua/base-test-api/base_test_api/bandit-report.json -f json  # Gera o relatório nesse diretório

      # Passo 6: Upload do relatório gerado
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: devops/garapua/base-test-api/base_test_api/bandit-report.json  # Ajuste o caminho

      # Passo 7: Verificar falhas se vulnerabilidades forem encontradas
      - name: Fail if vulnerabilities found
        if: failure()
        run: |
          echo "Bandit found vulnerabilities. Check the report for details."
          exit 1
